# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    redirectionListener:
            class: AppBundle\Listener\redirectionListener
            arguments: ['@service_container']
            tags:
                - { name : kernel.event_listener , event : kernel.request,method : onKernelRequest}