deals_index:
    path:     /
    defaults: { _controller: "AppBundle:Deals:index" }
    methods:  GET

deals_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Deals:show" }
    methods:  GET

deals_new:
    path:     /new
    defaults: { _controller: "AppBundle:Deals:new" }
    methods:  [GET, POST]

deals_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Deals:edit" }
    methods:  [GET, POST]

deals_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Deals:delete" }
    methods:  DELETE
