services:
#    user.example:
#        class: UserBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    redirect.after.login:
        class: AppBundle\Redirection\AfterLoginRedirection
        arguments: ["@router"]
